"""add last_played_date to user_stats

Revision ID: 47dddd3abc5c
Revises: 0953ec57d3ba
Create Date: 2026-06-24 12:01:01.532071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47dddd3abc5c'
down_revision: Union[str, Sequence[str], None] = '0953ec57d3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stats', sa.Column('last_played_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'last_played_date')
    # ### end Alembic commands ###
