"""add promotion_tier to characters

Revision ID: 692ee0101dd5
Revises: 47dddd3abc5c
Create Date: 2026-06-24 17:51:44.089436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692ee0101dd5'
down_revision: Union[str, Sequence[str], None] = '47dddd3abc5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('promotion_tier', sa.String(length=20), server_default='Unpromoted', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'promotion_tier')
    # ### end Alembic commands ###
